// src/components/skytrip/FlightList.vue
<template>
  <div class="flight-list">
    <h3 v-if="title" class="title is-4">{{ title }}</h3>
    <div v-for="(flight, index) in flights" :key="index" class="flight-item">
      <FlightCard
        v-if="variant === 'detailed'"
        v-bind="flight"
        :variant="variant"
      />
      <div v-else class="flight-summary">
        <p>{{ flight.from.city }} → {{ flight.to.city }}</p>
        <p>{{ flight.departureTime }} - {{ flight.arrivalTime }}</p>
        <p v-if="flight.price">{{ flight.price }}</p>
      </div>
    </div>
    <a v-if="showSeeAll" class="button is-text">See All</a>
  </div>
</template>

<script setup lang="ts">
import FlightCard from './FlightCard.vue';

interface Flight {
  from: { code: string; city: string };
  to: { code: string; city: string };
  departureTime: string;
  arrivalTime: string;
  duration?: string;
  airline?: string;
  price?: string;
}

interface Props {
  flights: Flight[];
  title?: string;
  showSeeAll?: boolean;
  variant?: 'default' | 'detailed';
}

withDefaults(defineProps<Props>(), {
  variant: 'default'
});
</script>

// src/components/skytrip/FlightList.tsx
import React from 'react';
import FlightCard from './FlightCard';
import './FlightList.scss';

interface Flight {
    from: {
        code: string;
        city: string;
    };
    to: {
        code: string;
        city: string;
    };
    departureTime: string;
    arrivalTime: string;
    duration: string;
    airline: string;
    price: string;
    header?: React.ReactNode;
    footer?: React.ReactNode;
}

interface FlightListProps {
    flights: Flight[];
    variant?: 'default' | 'compact' | 'detailed';
    title?: string;
    showSeeAll?: boolean;
    onSeeAll?: () => void;
}

const FlightList: React.FC<FlightListProps> = ({
    flights,
    variant = 'default',
    title,
    showSeeAll = true,
    onSeeAll
}) => {
    return (
        <div className="skytrip-flight-list">
            {(title || showSeeAll) && (
                <div className="section-header">
                    {title && <h3>{title}</h3>}
                    {showSeeAll && (
                        <a href="#" className="see-all" onClick={(e) => {
                            e.preventDefault();
                            onSeeAll?.();
                        }}>
                            See All
                        </a>
                    )}
                </div>
            )}
            <div className="flights">
                {flights.map((flight, index) => (
                    <FlightCard
                        key={index}
                        from={flight.from}
                        to={flight.to}
                        departureTime={flight.departureTime}
                        arrivalTime={flight.arrivalTime}
                        duration={flight.duration}
                        airline={flight.airline}
                        price={flight.price}
                        variant={variant}
                        header={flight.header}
                        footer={flight.footer}
                    />
                ))}
            </div>
        </div>
    );
};

export default FlightList;
