// src/components/skytrip/PageHeader.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Menu, Search, Bell } from 'lucide-react';
import { useSidebar } from '@/contexts/SidebarContext';
import Avatar from '@/components/Avatar';
import './PageHeader.scss';

interface PageHeaderProps {
    title: string;
    subtitle?: string;
    leftAction?: 'menu' | 'back';
    showBack?: boolean;
    backUrl?: string;
    onBack?: () => void;
    onMenu?: () => void;
    showSearch?: boolean;
    onSearch?: () => void;
    showMenu?: boolean;
    showAvatar?: boolean;
    showNotification?: boolean;
    /** When true, highlights the bell with a badge to indicate pending notifications. */
    hasPendingNotifications?: boolean;
    avatarUrl?: string;
    onAvatarClick?: () => void;
    onNotificationClick?: () => void;
    variant?: 'default' | 'with-route';
    children?: React.ReactNode;
}

const PageHeader: React.FC<PageHeaderProps> = ({
    title,
    subtitle,
    leftAction,
    showBack = false,
    backUrl,
    onBack,
    onMenu,
    showSearch = false,
    onSearch,
    showAvatar = true,
    showNotification = true,
    hasPendingNotifications = false,
    avatarUrl = 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
    onAvatarClick,
    onNotificationClick,
    children
}) => {
    const navigate = useNavigate();
    const { toggleSidebar } = useSidebar();
    const resolvedLeftAction = leftAction ?? (showBack ? 'back' : 'menu');

    const handleBack = () => {
        if (onBack) {
            onBack();
        } else if (backUrl) {
            navigate(backUrl);
        } else {
            navigate(-1);
        }
    };

    const handleMenu = () => {
        if (onMenu) {
            onMenu();
            return;
        }

        // Default to toggling the shared sidebar drawer when no handler is provided.
        toggleSidebar();
    };

    return (
        <header className='skytrip-page-header'>
            <div className="header-top">
                <div className="left-actions">
                    {resolvedLeftAction === 'back' ? (
                        <button onClick={handleBack} className="icon-button back-button">
                            <ArrowLeft size={20} strokeWidth={2} />
                        </button>
                    ) : (
                        <button onClick={handleMenu} className="icon-button menu-button">
                            <Menu size={20} strokeWidth={2} />
                        </button>
                    )}
                </div>

                <div className="title-block">
                    <h1>{title}</h1>
                    {subtitle && <p className="subtitle">{subtitle}</p>}
                </div>

                <div className="right-actions">
                    {showSearch && (
                        <button className="icon-button search-button" onClick={onSearch}>
                            <Search size={20} strokeWidth={2} />
                        </button>
                    )}
                    {showNotification && (
                        <button
                            className={`icon-button notification${hasPendingNotifications ? ' is-pending' : ''}`}
                            onClick={onNotificationClick}
                        >
                            <Bell size={20} />
                        </button>
                    )}
                    {showAvatar && (
                        <div className="avatar-wrapper">
                            <Avatar
                                variant="compact"
                                fallbackPicture={avatarUrl}
                                fallbackName={title}
                            />
                        </div>
                    )}
                </div>
            </div>

        {children}
        </header>
    );
};

export default PageHeader;

// src/components/skytrip/PageHeader.vue
<template>
  <header class="skytrip-page-header">
    <div class="header-top">
      <div class="left-actions">
        <button v-if="resolvedLeftAction === 'back'" @click="handleBack" class="icon-button back-button">
          <ArrowLeft :size="20" :stroke-width="2" />
        </button>
        <button v-else @click="handleMenu" class="icon-button menu-button">
          <Menu :size="20" :stroke-width="2" />
        </button>
      </div>

      <div class="title-block">
        <h1>{{ title }}</h1>
        <p v-if="subtitle" class="subtitle">{{ subtitle }}</p>
      </div>

      <div class="right-actions">
        <button v-if="showSearch" class="icon-button search-button" @click="onSearch">
          <Search :size="20" :stroke-width="2" />
        </button>
        <button
          v-if="showNotification"
          :class="['icon-button', 'notification', { 'is-pending': hasPendingNotifications }]"
          @click="onNotificationClick"
        >
          <Bell :size="20" />
        </button>
        <div v-if="showAvatar" class="avatar-wrapper">
          <Avatar
            variant="compact"
            :fallback-picture="avatarUrl"
            :fallback-name="title"
          />
        </div>
      </div>
    </div>

    <slot />
  </header>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import { ArrowLeft, Menu, Search, Bell } from 'lucide-vue-next';
import { useSidebar } from '@/composables/useSidebar';
import Avatar from '@/components/Avatar.vue';
import './PageHeader.scss';

interface PageHeaderProps {
  title: string;
  subtitle?: string;
  leftAction?: 'menu' | 'back';
  showBack?: boolean;
  backUrl?: string;
  onBack?: () => void;
  onMenu?: () => void;
  showSearch?: boolean;
  onSearch?: () => void;
  showMenu?: boolean;
  showAvatar?: boolean;
  showNotification?: boolean;
  hasPendingNotifications?: boolean;
  avatarUrl?: string;
  onAvatarClick?: () => void;
  onNotificationClick?: () => void;
  variant?: 'default' | 'with-route';
}

const props = withDefaults(defineProps<PageHeaderProps>(), {
  showBack: false,
  showSearch: false,
  showAvatar: true,
  showNotification: true,
  hasPendingNotifications: false,
  avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
  variant: 'default'
});

const router = useRouter();
const { toggleSidebar } = useSidebar();
const resolvedLeftAction = computed(() => props.leftAction ?? (props.showBack ? 'back' : 'menu'));

const handleBack = () => {
  if (props.onBack) {
    props.onBack();
  } else if (props.backUrl) {
    router.push(props.backUrl);
  } else {
    router.back();
  }
};

const handleMenu = () => {
  if (props.onMenu) {
    props.onMenu();
    return;
  }
  toggleSidebar();
};
</script>
