// src/components/skytrip/Tabs.tsx
import React from 'react';
import './Tabs.scss';

interface Tab {
    label: string;
    value: string;
}

interface TabsProps {
    tabs: Tab[];
    activeTab: string;
    onTabChange: (value: string) => void;
    variant?: 'default' | 'rounded';
}

const Tabs: React.FC<TabsProps> = ({ tabs, activeTab, onTabChange, variant = 'default' }) => {
    const className = `skytrip-tabs ${variant === 'rounded' ? 'rounded' : ''}`;
    
    return (
        <div className={className}>
            {tabs.map((tab) => (
                <button
                    key={tab.value}
                    className={`tab-button ${activeTab === tab.value ? 'active' : ''}`}
                    onClick={() => onTabChange(tab.value)}
                >
                    {tab.label}
                </button>
            ))}
        </div>
    );
};

export default Tabs;

// src/components/skytrip/Tabs.vue
<template>
  <div class="tabs-container">
    <div :class="['tabs', variant === 'rounded' ? 'is-rounded' : '']">
      <ul>
        <li
          v-for="tab in tabs"
          :key="tab.value"
          :class="{ 'is-active': activeTab === tab.value }"
        >
          <a @click="$emit('tab-change', tab.value)">{{ tab.label }}</a>
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
interface Tab {
  label: string;
  value: string;
}

interface Props {
  tabs: Tab[];
  activeTab: string;
  variant?: 'default' | 'rounded';
}

withDefaults(defineProps<Props>(), {
  variant: 'default'
});

defineEmits<{
  'tab-change': [value: string];
}>();
</script>
