// src/pages/CommercialModes.jsx
import React, { useState, useEffect } from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header';
import { getCommercialModes } from '../services/navitiaApi';

const CommercialModes = () => {
    const [modes, setModes] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchModes = async () => {
            try {
                setLoading(true);
                const response = await getCommercialModes();
                const data = response.data;
                setModes(data.commercial_modes || []);
                setError(null);
            } catch (err) {
                setError('Erreur lors du chargement des modes de transport');
                console.error(err);
            } finally {
                setLoading(false);
            }
        };

        fetchModes();
    }, []);

    return (
        <>
            <Header />
            <div className='commercial-modes'>
                <div className='commercial-modes__content-wrapper'>
                    <h1 className='commercial-modes__title'>
                        Modes de transport <span>SNCF</span>
                    </h1>

                    {loading && (
                        <div className='loading'>
                            <p>Chargement des modes de transport...</p>
                        </div>
                    )}

                    {error && (
                        <div className='error'>
                            <p>{error}</p>
                        </div>
                    )}

                    {!loading && !error && (
                        <div className='modes-list'>
                            {modes.length === 0 ? (
                                <p>Aucun mode de transport trouvé</p>
                            ) : (
                                modes.map((mode) => (
                                    <div key={mode.id} className='mode-card'>
                                        <h3 className='mode-card__name'>
                                            {mode.name || 'Non spécifié'}
                                        </h3>
                                        <p className='mode-card__id'>
                                            ID: {mode.id}
                                        </p>
                                    </div>
                                ))
                            )}
                        </div>
                    )}
                </div>
            </div>
            <Footer />
        </>
    );
};

export default CommercialModes;

// src/pages/CommercialModes.vue
<template>
  <div>
    <PageHeader
      title="Modes de transport SNCF"
      subtitle="Découvrez les modes commerciaux disponibles dans l'API"
      :show-notification="false"
    />
    <section class="section">
      <div class="container">
        <CommercialModesLoadingState v-if="loading" />
        <CommercialModesErrorState
          v-if="error"
          :error="error"
          @dismiss="error = null"
        />
        <CommercialModesList v-if="!loading && !error" :modes="modes" />
      </div>
    </section>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import Footer from '@/components/Footer.vue';
import { PageHeader } from '@/components/skytrip';
import { getCommercialModes } from '@/services/navitiaApi';
import type { CommercialMode } from '@/client/models/commercial-mode';
import CommercialModesLoadingState from '@/components/commercialModes/CommercialModesLoadingState.vue';
import CommercialModesErrorState from '@/components/commercialModes/CommercialModesErrorState.vue';
import CommercialModesList from '@/components/commercialModes/CommercialModesList.vue';

const modes = ref<CommercialMode[]>([]);
const loading = ref<boolean>(true);
const error = ref<string | null>(null);

onMounted(async () => {
  try {
    loading.value = true;
    const data = await getCommercialModes();
    modes.value = data.commercial_modes || [];
    error.value = null;
  } catch (err) {
    error.value = 'Erreur lors du chargement des modes de transport';
    console.error(err);
  } finally {
    loading.value = false;
  }
});
</script>
