// src/pages/CommercialModes.tsx
import React, { useState, useEffect } from 'react';
import Footer from '@/components/Footer';
import { PageHeader } from '@/components/skytrip';
import { getCommercialModes } from '@/services/navitiaApi';
import type { CommercialMode } from '@/client/models/commercial-mode';
import CommercialModesLoadingState from '@/components/commercialModes/CommercialModesLoadingState';
import CommercialModesErrorState from '@/components/commercialModes/CommercialModesErrorState';
import CommercialModesList from '@/components/commercialModes/CommercialModesList';

const CommercialModes: React.FC = () => {
    const [modes, setModes] = useState<CommercialMode[]>([]);
    const [loading, setLoading] = useState<boolean>(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchModes = async (): Promise<void> => {
            try {
                setLoading(true);
                const data = await getCommercialModes();
                setModes(data.commercial_modes || []);
                setError(null);
            } catch (err) {
                setError('Erreur lors du chargement des modes de transport');
                console.error(err);
            } finally {
                setLoading(false);
            }
        };

        fetchModes();
    }, []);

    return (
        <>
            <PageHeader
                title="Modes de transport SNCF"
                subtitle="Découvrez les modes commerciaux disponibles dans l'API"
                showNotification={false}
                
            />
            <section className='section'>
                <div className='container'>
                    {loading && <CommercialModesLoadingState />}

                    {error && (
                        <CommercialModesErrorState
                            error={error}
                            onDismiss={() => setError(null)}
                        />
                    )}

                    {!loading && !error && <CommercialModesList modes={modes} />}
                </div>
            </section>
            <Footer />
        </>
    );
};

export default CommercialModes;

// src/pages/CommercialModes.vue
<template>
  <div>
    <PageHeader
      title="Modes de transport SNCF"
      subtitle="Découvrez les modes commerciaux disponibles dans l'API"
      :show-notification="false"
    />
    <section class="section">
      <div class="container">
        <CommercialModesLoadingState v-if="loading" />
        <CommercialModesErrorState
          v-if="error"
          :error="error"
          @dismiss="error = null"
        />
        <CommercialModesList v-if="!loading && !error" :modes="modes" />
      </div>
    </section>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import Footer from '@/components/Footer.vue';
import { PageHeader } from '@/components/skytrip';
import { getCommercialModes } from '@/services/navitiaApi';
import type { CommercialMode } from '@/client/models/commercial-mode';
import CommercialModesLoadingState from '@/components/commercialModes/CommercialModesLoadingState.vue';
import CommercialModesErrorState from '@/components/commercialModes/CommercialModesErrorState.vue';
import CommercialModesList from '@/components/commercialModes/CommercialModesList.vue';

const modes = ref<CommercialMode[]>([]);
const loading = ref<boolean>(true);
const error = ref<string | null>(null);

onMounted(async () => {
  try {
    loading.value = true;
    const data = await getCommercialModes();
    modes.value = data.commercial_modes || [];
    error.value = null;
  } catch (err) {
    error.value = 'Erreur lors du chargement des modes de transport';
    console.error(err);
  } finally {
    loading.value = false;
  }
});
</script>
