// src/pages/Coverage.jsx
import React, { useState, useEffect } from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header';
import { getCoverage, getCoverageDetails } from '../services/navitiaApi';

const Coverage = () => {
    const [coverages, setCoverages] = useState([]);
    const [selectedCoverage, setSelectedCoverage] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchCoverages = async () => {
            try {
                setLoading(true);
                const response = await getCoverage();
                const data = response.data;
                setCoverages(data.regions || []);
                setError(null);
            } catch (err) {
                setError('Erreur lors du chargement des zones de couverture');
                console.error(err);
            } finally {
                setLoading(false);
            }
        };

        fetchCoverages();
    }, []);

    const handleCoverageClick = async (coverageId) => {
        try {
            setLoading(true);
            const response = await getCoverageDetails(coverageId);
            const data = response.data;
            setSelectedCoverage({ id: coverageId, ...data });
            setError(null);
        } catch (err) {
            setError('Erreur lors du chargement des détails');
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    return (
        <>
            <Header />
            <div className='coverage-page'>
                <div className='coverage-page__content-wrapper'>
                    <h1 className='coverage-page__title'>
                        Zones de <span>couverture</span>
                    </h1>

                    {loading && !selectedCoverage && (
                        <div className='loading'>
                            <p>Chargement des zones de couverture...</p>
                        </div>
                    )}

                    {error && (
                        <div className='error'>
                            <p>{error}</p>
                        </div>
                    )}

                    {!loading && !selectedCoverage && (
                        <div className='coverages-list'>
                            {coverages.length === 0 ? (
                                <p>Aucune zone de couverture trouvée</p>
                            ) : (
                                coverages.map((coverage) => (
                                    <div
                                        key={coverage.id}
                                        className='coverage-card'
                                        onClick={() => handleCoverageClick(coverage.id)}
                                    >
                                        <h3 className='coverage-card__name'>{coverage.id}</h3>
                                        <p className='coverage-card__status'>
                                            Statut: {coverage.status || 'N/A'}
                                        </p>
                                    </div>
                                ))
                            )}
                        </div>
                    )}

                    {selectedCoverage && (
                        <div className='coverage-details'>
                            <button
                                className='back-button'
                                onClick={() => setSelectedCoverage(null)}
                            >
                                ← Retour
                            </button>
                            <h2>Détails: {selectedCoverage.id}</h2>
                            <div className='details-content'>
                                <pre>{JSON.stringify(selectedCoverage, null, 2)}</pre>
                            </div>
                        </div>
                    )}
                </div>
            </div>
            <Footer />
        </>
    );
};

export default Coverage;

// src/pages/Coverage.vue
<template>
  <div>
    <PageHeader
      title="Zones de couverture"
      subtitle="Consultez les régions et réseaux disponibles"
      :show-notification="false"
    />
    <section class="section">
      <div class="container">
        <div v-if="loading && !selectedCoverage" class="box has-text-centered">
          <div class="loader-wrapper">
            <div class="loader is-loading"></div>
          </div>
          <p class="mt-4 subtitle is-5">Chargement des zones de couverture...</p>
        </div>

        <div v-if="error" class="notification is-danger">
          <button class="delete" @click="error = null"></button>
          <p class="title is-5">Erreur</p>
          <p>{{ error }}</p>
        </div>

        <template v-if="!loading && !selectedCoverage">
          <CoverageContext v-if="coverageResponse?.context" :context="coverageResponse.context" />
          <CoverageList
            :coverages="coverages"
            :coverage-response="coverageResponse"
            @coverage-click="handleCoverageClick"
          />
        </template>

        <CoverageDetail
          v-if="selectedCoverage"
          :selected-coverage="selectedCoverage"
          @back="selectedCoverage = null"
        />
      </div>
    </section>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import Footer from '@/components/Footer.vue';
import { PageHeader } from '@/components/skytrip';
import { getCoverage, getCoverageDetails } from '@/services/navitiaApi';
import type { CoverageResponse, Coverage } from '@/client/models';
import type { Link } from '@/client/models/link';
import type { Context } from '@/client/models/context';
import { CoverageContext, CoverageList, CoverageDetail } from '@/components/coverage';

interface SelectedCoverage extends Coverage {
  id: string;
  context?: Context;
  links?: Link[];
}

const coverages = ref<Coverage[]>([]);
const coverageResponse = ref<CoverageResponse | null>(null);
const selectedCoverage = ref<SelectedCoverage | null>(null);
const loading = ref<boolean>(true);
const error = ref<string | null>(null);

onMounted(async () => {
  try {
    loading.value = true;
    const data = await getCoverage();
    coverages.value = data.regions || [];
    coverageResponse.value = data;
    error.value = null;
  } catch (err) {
    error.value = 'Erreur lors du chargement des zones de couverture';
    console.error(err);
  } finally {
    loading.value = false;
  }
});

const handleCoverageClick = async (coverageId: string | undefined): Promise<void> => {
  if (!coverageId) return;
  
  try {
    loading.value = true;
    const data = await getCoverageDetails(coverageId);
    selectedCoverage.value = { id: coverageId, ...data } as SelectedCoverage;
    error.value = null;
  } catch (err) {
    error.value = 'Erreur lors du chargement des détails';
    console.error(err);
  } finally {
    loading.value = false;
  }
};
</script>
