// src/pages/Favorites.tsx

import React, { useState, useEffect } from 'react';
import { getFavorites, removeFavorite, type FavoriteLocation } from '@/services/favoritesService';
import { Star, MapPin, Loader2 } from 'lucide-react';
import FavoritesTable from '@/components/favorites/FavoritesTable';
import Footer from '@/components/Footer';
import { PageHeader } from '@/components/skytrip';

const Favorites: React.FC = () => {
    const [favorites, setFavorites] = useState<FavoriteLocation[]>([]);
    const [loading, setLoading] = useState<boolean>(true);

    useEffect(() => {
        const fetchFavorites = async () => {
            setLoading(true);
            const favs = await getFavorites();
            setFavorites(favs);
            setLoading(false);
        };
        fetchFavorites();
    }, []);

    const handleRemoveFavorite = async (id: string) => {
        await removeFavorite(id);
        const updatedFavorites = await getFavorites();
        setFavorites(updatedFavorites);
    };

    return (
        <>
            <PageHeader
                title="Vos favoris"
                subtitle="Retrouvez rapidement vos gares et lieux sauvegardés"
                showNotification={false}
                showAvatar={false}
            />
            <section className='section'>
                <div className='container'>
                    {loading ? (
                        <div className="has-text-centered">
                            <Loader2 className="animate-spin" size={48} />
                            <p className="is-size-4 mt-4">Chargement des favoris...</p>
                        </div>
                    ) : favorites.length > 0 ? (
                        <FavoritesTable
                            favorites={favorites}
                            onRemoveFavorite={handleRemoveFavorite}
                        />
                    ) : (
                        <div className='message is-info'>
                            <div className='message-body'>
                                <p className='is-size-5'>
                                    <MapPin className='icon' />
                                    Vous n'avez pas encore de favoris.
                                </p>
                                <p>
                                    Pour ajouter un favori, recherchez un lieu ou une gare et cliquez sur l'étoile.
                                </p>
                            </div>
                        </div>
                    )}
                </div>
            </section>
            <Footer />
        </>
    );
};

export default Favorites;

// src/pages/Favorites.vue
<template>
  <div>
    <PageHeader
      title="Vos favoris"
      subtitle="Retrouvez rapidement vos gares et lieux sauvegardés"
      :show-notification="false"
    />
    <section class="section">
      <div class="container">
        <div v-if="loading" class="has-text-centered">
          <Loader2 class="animate-spin" :size="48" />
          <p class="is-size-4 mt-4">Chargement des favoris...</p>
        </div>
        <FavoritesTable
          v-else-if="favorites.length > 0"
          :favorites="favorites"
          @remove-favorite="handleRemoveFavorite"
        />
        <div v-else class="message is-info">
          <div class="message-body">
            <p class="is-size-5">
              <MapPin class="icon" />
              Vous n'avez pas encore de favoris.
            </p>
            <p>
              Pour ajouter un favori, recherchez un lieu ou une gare et cliquez sur l'étoile.
            </p>
          </div>
        </div>
      </div>
    </section>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Star, MapPin, Loader2 } from 'lucide-vue-next';
import { getFavorites, removeFavorite, type FavoriteLocation } from '@/services/favoritesService';
import FavoritesTable from '@/components/favorites/FavoritesTable.vue';
import Footer from '@/components/Footer.vue';
import { PageHeader } from '@/components/skytrip';

const favorites = ref<FavoriteLocation[]>([]);
const loading = ref<boolean>(true);

onMounted(async () => {
  loading.value = true;
  favorites.value = await getFavorites();
  loading.value = false;
});

const handleRemoveFavorite = async (id: string) => {
  await removeFavorite(id);
  favorites.value = await getFavorites();
};
</script>
