// src/pages/Favorites.jsx
import React, { useState, useEffect } from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { getFavorites, removeFavorite } from '../services/favoritesService';

const Favorites = () => {
    const [favorites, setFavorites] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadFavorites();
    }, []);

    const loadFavorites = () => {
        setLoading(true);
        const favs = getFavorites();
        setFavorites(favs);
        setLoading(false);
    };

    const handleRemoveFavorite = (id) => {
        removeFavorite(id);
        loadFavorites();
    };

    const formatDate = (dateString) => {
        if (!dateString) return 'Date inconnue';
        try {
            const date = new Date(dateString);
            return date.toLocaleDateString('fr-FR', {
                day: '2-digit',
                month: '2-digit',
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
            });
        } catch {
            return 'Date inconnue';
        }
    };

    return (
        <>
            <Header />
            <section className='section'>
                <div className='container'>
                    <div className='level mb-5'>
                        <div className='level-left'>
                            <div className='level-item'>
                                <h1 className='title is-2'>
                                    <span className='icon has-text-warning mr-3'><i className='fas fa-star'></i></span>
                                    Favoris
                                </h1>
                            </div>
                        </div>
                    </div>

                    {loading ? (
                        <div className='box has-text-centered'>
                            <div className='loader-wrapper'>
                                <div className='loader is-loading'></div>
                            </div>
                            <p className='mt-4 subtitle is-5'>Chargement des favoris...</p>
                        </div>
                    ) : favorites.length === 0 ? (
                        <div className='box has-text-centered'>
                            <div className='content'>
                                <span className='icon is-large has-text-grey mb-4' style={{fontSize: '4rem'}}>⭐</span>
                                <h2 className='title is-4'>Aucun favori</h2>
                                <p className='subtitle is-6 has-text-grey'>
                                    Vous n'avez pas encore de gares favorites.
                                </p>
                                <p className='has-text-grey'>
                                    Utilisez l'étoile dans les champs de recherche pour ajouter des gares à vos favoris.
                                </p>
                            </div>
                        </div>
                    ) : (
                        <div className='box'>
                            <h2 className='title is-4 mb-5'>
                                Mes gares favorites <span className='tag is-primary is-medium'>{favorites.length}</span>
                            </h2>
                            <div className='table-container'>
                                <table className='table is-fullwidth is-striped is-hoverable'>
                                    <thead>
                                        <tr>
                                            <th>Nom</th>
                                            <th>Type</th>
                                            <th>Ajouté le</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {favorites.map((favorite) => (
                                            <tr key={favorite.id}>
                                                <td>
                                                    <strong>{favorite.name}</strong>
                                                </td>
                                                <td>
                                                    <span className='tag is-light'>
                                                        {favorite.type === 'stop_area' ? 'Gare' : 'Point d\'arrêt'}
                                                    </span>
                                                </td>
                                                <td>
                                                    <span className='has-text-grey'>{formatDate(favorite.addedAt)}</span>
                                                </td>
                                                <td>
                                                    <button
                                                        className='button is-small is-danger is-light'
                                                        onClick={() => handleRemoveFavorite(favorite.id)}
                                                        title='Retirer des favoris'
                                                    >
                                                        <span className='icon'>
                                                            <i className='fas fa-trash'></i>
                                                        </span>
                                                        <span>Retirer</span>
                                                    </button>
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    )}
                </div>
            </section>
            <Footer />
        </>
    );
};

export default Favorites;

// src/pages/Favorites.vue
<template>
  <div>
    <PageHeader
      title="Vos favoris"
      subtitle="Retrouvez rapidement vos gares et lieux sauvegardés"
      :show-notification="false"
    />
    <section class="section">
      <div class="container">
        <div v-if="loading" class="has-text-centered">
          <Loader2 class="animate-spin" :size="48" />
          <p class="is-size-4 mt-4">Chargement des favoris...</p>
        </div>
        <FavoritesTable
          v-else-if="favorites.length > 0"
          :favorites="favorites"
          @remove-favorite="handleRemoveFavorite"
        />
        <div v-else class="message is-info">
          <div class="message-body">
            <p class="is-size-5">
              <MapPin class="icon" />
              Vous n'avez pas encore de favoris.
            </p>
            <p>
              Pour ajouter un favori, recherchez un lieu ou une gare et cliquez sur l'étoile.
            </p>
          </div>
        </div>
      </div>
    </section>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { Star, MapPin, Loader2 } from 'lucide-vue-next';
import { getFavorites, removeFavorite, type FavoriteLocation } from '@/services/favoritesService';
import FavoritesTable from '@/components/favorites/FavoritesTable.vue';
import Footer from '@/components/Footer.vue';
import { PageHeader } from '@/components/skytrip';

const favorites = ref<FavoriteLocation[]>([]);
const loading = ref<boolean>(true);

onMounted(async () => {
  loading.value = true;
  favorites.value = await getFavorites();
  loading.value = false;
});

const handleRemoveFavorite = async (id: string) => {
  await removeFavorite(id);
  favorites.value = await getFavorites();
};
</script>
