// src/pages/Sample2.vue
<template>
  <div class="app-flight">
    <PageHeader
      title="Saved Flights"
      subtitle="Retrouvez vos vols enregistrés"
      back-url="/"
      :show-search="true"
    />
    <main>
      <div class="skytrip-flight-card">
        <Tabs
          :tabs="tabs"
          :active-tab="activeTab"
          @tab-change="activeTab = $event"
          variant="rounded"
        />
      </div>
      <div class="saved-flights">
        <FlightCard
          v-for="(flight, index) in flights"
          :key="index"
          :from="flight.from"
          :to="flight.to"
          :departure-time="flight.departureTime"
          :arrival-time="flight.arrivalTime"
          :duration="flight.duration"
          :airline="flight.airline"
          variant="saved"
          :show-timeline="false"
          :header="flight.header"
          :footer="flight.footer"
          :flight-type="flight.flightType"
        />
      </div>
    </main>
  </div>
</template>

<script setup lang="ts">
import { ref, h } from 'vue';
import { PageHeader, Tabs, FlightCard } from '@/components/skytrip';
import { PlaneTakeoff, Bookmark } from 'lucide-vue-next';

const activeTab = ref('active');

const tabs = [
  { label: 'Active', value: 'active' },
  { label: 'Expired', value: 'expired' }
];

const flights = [
  {
    from: { code: 'JFK', city: 'New York' },
    to: { code: 'HKG', city: 'HKG' },
    departureTime: '09:30',
    arrivalTime: '21:45',
    duration: '12h 15m',
    airline: 'Cathay Pacific',
    flightType: 'Direct',
    header: h('div', { class: 'flight-header' }, [
      h('div', { class: 'airline' }, [
        h(PlaneTakeoff, { size: 20 }),
        h('span', 'Cathay Pacific')
      ]),
      h(Bookmark, { size: 20 })
    ]),
    footer: h('div', { class: 'flight-footer' }, [
      h('span', { class: 'date' }, 'Mon, Dec 18 2023'),
      h('button', { class: 'status-button' }, 'Active')
    ])
  }
];
</script>

// src/pages/Sample2.tsx
import React, { useState } from 'react';
import { PageHeader, Tabs, FlightCard } from '@/components/skytrip';
import { PlaneTakeoff, Bookmark } from 'lucide-react';

const Sample2: React.FC = () => {
  const [activeTab, setActiveTab] = useState('active');

  const tabs = [
    { label: 'Active', value: 'active' },
    { label: 'Expired', value: 'expired' }
  ];

  const flights = [
    {
      from: { code: 'JFK', city: 'New York' },
      to: { code: 'HKG', city: 'HKG' },
      departureTime: '09:30',
      arrivalTime: '21:45',
      duration: '12h 15m',
      airline: 'Cathay Pacific',
      flightType: 'Direct',
      header: (
        <>
          <div className="airline">
            <PlaneTakeoff size={20} />
            <span>Cathay Pacific</span>
          </div>
          <Bookmark size={20} />
        </>
      ),
      footer: (
        <>
          <span className="date">Mon, Dec 18 2023</span>
          <button className="status-button">Active</button>
        </>
      )
    },
    {
      from: { code: 'JFK', city: 'New York' },
      to: { code: 'HKG', city: 'HKG' },
      departureTime: '09:30',
      arrivalTime: '21:45',
      duration: '12h 15m',
      airline: 'Cathay Pacific',
      flightType: 'Direct',
      header: (
        <>
          <div className="airline">
            <PlaneTakeoff size={20} />
            <span>Cathay Pacific</span>
          </div>
          <Bookmark size={20} />
        </>
      ),
      footer: (
        <>
          <span className="date">Mon, Dec 18 2023</span>
          <button className="status-button">Active</button>
        </>
      )
    },
    {
      from: { code: 'JFK', city: 'New York' },
      to: { code: 'HKG', city: 'HKG' },
      departureTime: '09:30',
      arrivalTime: '21:45',
      duration: '12h 15m',
      airline: 'Cathay Pacific',
      flightType: 'Direct',
      header: (
        <>
          <div className="airline">
            <PlaneTakeoff size={20} />
            <span>Cathay Pacific</span>
          </div>
          <Bookmark size={20} />
        </>
      ),
      footer: (
        <>
          <span className="date">Mon, Dec 18 2023</span>
          <button className="status-button">Active</button>
        </>
      )
    }
  ];

  return (
    <div className="app-flight">
      <PageHeader
        title="Saved Flights"
        subtitle="Retrouvez vos vols enregistrés"
        backUrl="/"
        showSearch={true}
      />
      <main>
          <div className="skytrip-flight-card">
              <Tabs
              tabs={tabs}
              activeTab={activeTab}
              onTabChange={setActiveTab}
              variant="rounded"
            />
          </div>
        <div className="saved-flights">
          {flights.map((flight, index) => (
            <FlightCard
              key={index}
              from={flight.from}
              to={flight.to}
              departureTime={flight.departureTime}
              arrivalTime={flight.arrivalTime}
              duration={flight.duration}
              airline={flight.airline}
              variant="saved"
              showTimeline={false}
              header={flight.header}
              footer={flight.footer}
              flightType={flight.flightType}
            />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Sample2;
