// src/pages/Schedules.vue
<template>
  <div>
    <PageHeader
      title="Horaires et planning"
      subtitle="Consultez les horaires par arrêt, ligne ou terminus"
      :show-notification="false"
    />
    <section class="section">
      <div class="container">
        <div class="box mb-5">
          <h3 class="title is-5 mb-4">Type de planning</h3>
          <div class="tabs is-boxed mb-4">
            <ul>
              <li :class="{ 'is-active': scheduleType === 'stop' }">
                <a @click="setScheduleType('stop')">
                  <span class="icon is-small"><MapPin :size="16" /></span>
                  <span>Horaires d'arrêt</span>
                </a>
              </li>
              <li :class="{ 'is-active': scheduleType === 'route' }">
                <a @click="setScheduleType('route')">
                  <span class="icon is-small"><Route :size="16" /></span>
                  <span>Horaires de ligne</span>
                </a>
              </li>
              <li :class="{ 'is-active': scheduleType === 'terminus' }">
                <a @click="setScheduleType('terminus')">
                  <span class="icon is-small"><Flag :size="16" /></span>
                  <span>Horaires terminus</span>
                </a>
              </li>
            </ul>
          </div>

          <form @submit.prevent="handleSearch">
            <div class="field">
              <label class="label" for="filter">Filtre</label>
              <div class="control">
                <input
                  id="filter"
                  class="input"
                  type="text"
                  v-model="filter"
                  placeholder="stop_area.id=stop_area:SNCF:87391003 ou line.id=line:SNCF:1"
                  :disabled="loading"
                />
              </div>
              <p class="help">
                Exemples: stop_area.id=stop_area:SNCF:87391003 ou line.id=line:SNCF:1
              </p>
            </div>

            <div class="field">
              <label class="label" for="datetime">Date et heure (optionnel)</label>
              <div class="control">
                <input
                  id="datetime"
                  class="input"
                  type="text"
                  v-model="datetime"
                  placeholder="20250113T152944"
                  :disabled="loading"
                />
              </div>
              <p class="help">Format: YYYYMMDDTHHmmss (ex: 20250113T152944)</p>
            </div>

            <div class="field">
              <div class="control">
                <button type="submit" class="button is-primary" :disabled="loading">
                  <span class="icon">
                    <Loader2 v-if="loading" :size="16" class="animate-spin" />
                    <Search v-else :size="16" />
                  </span>
                  <span>{{ loading ? 'Chargement...' : 'Rechercher' }}</span>
                </button>
              </div>
            </div>
          </form>
        </div>

        <div v-if="loading" class="box has-text-centered">
          <div class="loader-wrapper">
            <div class="loader is-loading"></div>
          </div>
          <p class="mt-4 subtitle is-5">Chargement des horaires...</p>
        </div>

        <div v-if="error" class="notification is-danger">
          <button class="delete" @click="error = null"></button>
          <p class="title is-5">Erreur</p>
          <p>{{ error }}</p>
        </div>

        <div v-if="!loading && schedules" class="box">
          <h2 class="title is-4 mb-5">Résultats</h2>
          <div class="content">
            <div class="table-container">
              <pre :style="{
                background: 'rgba(0, 0, 0, 0.3)',
                borderRadius: '10px',
                padding: '1.5rem',
                overflow: 'auto',
                color: '#ccc',
                fontFamily: '\'Roboto Mono\', monospace',
                fontSize: '0.9rem',
                whiteSpace: 'pre-wrap',
                wordWrap: 'break-word'
              }">{{ JSON.stringify(schedules, null, 2) }}</pre>
            </div>
          </div>
        </div>
      </div>
    </section>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { MapPin, Route, Flag, Loader2, Search } from 'lucide-vue-next';
import Footer from '@/components/Footer.vue';
import { PageHeader } from '@/components/skytrip';
import { getStopSchedules, getRouteSchedules, getTerminusSchedules, formatDateTime } from '@/services/navitiaApi';
import type { StopSchedulesResponse, RouteSchedulesResponse, TerminusSchedulesResponse } from '@/client/models';

const scheduleType = ref<'stop' | 'route' | 'terminus'>('stop');
const filter = ref<string>('');
const datetime = ref<string>('');
const schedules = ref<StopSchedulesResponse | RouteSchedulesResponse | TerminusSchedulesResponse | null>(null);
const loading = ref<boolean>(false);
const error = ref<string | null>(null);

const setScheduleType = (type: 'stop' | 'route' | 'terminus') => {
  scheduleType.value = type;
  schedules.value = null;
  error.value = null;
};

const handleSearch = async (): Promise<void> => {
  if (!filter.value.trim()) {
    error.value = 'Veuillez entrer un filtre';
    return;
  }

  try {
    loading.value = true;
    error.value = null;
    const searchDatetime = datetime.value || formatDateTime(new Date());
    let response;

    switch (scheduleType.value) {
      case 'stop':
        response = await getStopSchedules(filter.value, 'sncf', searchDatetime);
        break;
      case 'route':
        response = await getRouteSchedules(filter.value, 'sncf', searchDatetime);
        break;
      case 'terminus':
        response = await getTerminusSchedules(filter.value, 'sncf', searchDatetime);
        break;
      default:
        throw new Error('Type de planning invalide');
    }

    schedules.value = response;
  } catch (err) {
    error.value = 'Erreur lors de la récupération des horaires';
    console.error(err);
    schedules.value = null;
  } finally {
    loading.value = false;
  }
};
</script>

// src/pages/Schedules.jsx
import React, { useState } from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header';
import { getStopSchedules, getRouteSchedules, getTerminusSchedules, formatDateTime } from '../services/navitiaApi';

const Schedules = () => {
    const [scheduleType, setScheduleType] = useState('stop'); // 'stop', 'route', 'terminus'
    const [filter, setFilter] = useState('');
    const [datetime, setDatetime] = useState('');
    const [schedules, setSchedules] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const handleSearch = async (e) => {
        e.preventDefault();
        if (!filter.trim()) {
            setError('Veuillez entrer un filtre');
            return;
        }

        try {
            setLoading(true);
            setError(null);
            const searchDatetime = datetime || formatDateTime(new Date());
            let response;

            switch (scheduleType) {
                case 'stop':
                    response = await getStopSchedules(filter, 'sncf', searchDatetime);
                    break;
                case 'route':
                    response = await getRouteSchedules(filter, 'sncf', searchDatetime);
                    break;
                case 'terminus':
                    response = await getTerminusSchedules(filter, 'sncf', searchDatetime);
                    break;
                default:
                    throw new Error('Type de planning invalide');
            }

            setSchedules(response.data);
        } catch (err) {
            setError('Erreur lors de la récupération des horaires');
            console.error(err);
            setSchedules(null);
        } finally {
            setLoading(false);
        }
    };

    return (
        <>
            <Header />
            <div className='schedules-page'>
                <div className='schedules-page__content-wrapper'>
                    <h1 className='schedules-page__title'>
                        Horaires et <span>planning</span>
                    </h1>

                    <div className='schedule-tabs'>
                        <button
                            className={`tab-button ${scheduleType === 'stop' ? 'active' : ''}`}
                            onClick={() => {
                                setScheduleType('stop');
                                setSchedules(null);
                                setError(null);
                            }}
                        >
                            Horaires d'arrêt
                        </button>
                        <button
                            className={`tab-button ${scheduleType === 'route' ? 'active' : ''}`}
                            onClick={() => {
                                setScheduleType('route');
                                setSchedules(null);
                                setError(null);
                            }}
                        >
                            Horaires de ligne
                        </button>
                        <button
                            className={`tab-button ${scheduleType === 'terminus' ? 'active' : ''}`}
                            onClick={() => {
                                setScheduleType('terminus');
                                setSchedules(null);
                                setError(null);
                            }}
                        >
                            Horaires terminus
                        </button>
                    </div>

                    <form onSubmit={handleSearch} className='schedules-form'>
                        <div className='form-group'>
                            <label htmlFor='filter'>
                                Filtre (ex: stop_area.id=stop_area:SNCF:87391003 ou line.id=line:SNCF:1)
                            </label>
                            <input
                                id='filter'
                                type='text'
                                value={filter}
                                onChange={(e) => setFilter(e.target.value)}
                                placeholder='stop_area.id=stop_area:SNCF:87391003'
                                className='form-input'
                            />
                        </div>

                        <div className='form-group'>
                            <label htmlFor='datetime'>
                                Date et heure (optionnel, format: YYYYMMDDTHHmmss)
                            </label>
                            <input
                                id='datetime'
                                type='text'
                                value={datetime}
                                onChange={(e) => setDatetime(e.target.value)}
                                placeholder='20250113T152944'
                                className='form-input'
                            />
                        </div>

                        <button type='submit' className='form-button' disabled={loading}>
                            {loading ? 'Chargement...' : 'Rechercher'}
                        </button>
                    </form>

                    {error && (
                        <div className='error'>
                            <p>{error}</p>
                        </div>
                    )}

                    {!loading && schedules && (
                        <div className='schedules-result'>
                            <h2>Résultats</h2>
                            <div className='schedules-content'>
                                <pre>{JSON.stringify(schedules, null, 2)}</pre>
                            </div>
                        </div>
                    )}
                </div>
            </div>
            <Footer />
        </>
    );
};

export default Schedules;
