// src/components/home/DashboardSection.tsx
import React from 'react';
import DashboardCard from './DashboardCard';

interface DashboardCardData {
    title: string;
    description: string;
    path: string;
    icon: React.ComponentType<{ size?: number | string; className?: string }>;
    color?: 'primary' | 'secondary';
}

interface DashboardSectionProps {
    title: string;
    icon: React.ComponentType<{ size?: number | string; className?: string }>;
    cards: DashboardCardData[];
    columnsClass?: string;
    columnsWrapperClassName?: string;
}

const DashboardSection: React.FC<DashboardSectionProps> = ({
    title,
    icon: Icon,
    cards,
    columnsClass = 'is-one-third-tablet is-half-mobile',
    columnsWrapperClassName = ''
}) => {
    return (
        <div className='skytrip-search-card mb-6'>
            <h2 className='title is-3 mb-4'>
                <span className='icon mr-2'>
                    <Icon size={24} />
                </span>
                {title}
            </h2>
            <div className={`columns is-multiline ${columnsWrapperClassName}`.trim()}>
                {cards.map((card) => (
                    <div key={card.path} className={`column ${columnsClass}`}>
                        <DashboardCard {...card} />
                    </div>
                ))}
            </div>
        </div>
    );
};

export default DashboardSection;

// src/components/home/DashboardSection.vue
<template>
  <div class="skytrip-search-card mb-6">
    <h2 class="title is-3 mb-4">
      <span class="icon mr-2">
        <component :is="icon" :size="24" />
      </span>
      {{ title }}
    </h2>
    <div :class="['columns', 'is-multiline', columnsWrapperClassName].filter(Boolean).join(' ')">
      <div
        v-for="card in cards"
        :key="card.path"
        :class="['column', columnsClass]"
      >
        <DashboardCard v-bind="card" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Component } from 'vue';
import DashboardCard from './DashboardCard.vue';

interface DashboardCardData {
  title: string;
  description: string;
  path: string;
  icon: Component;
  color?: 'primary' | 'secondary';
}

interface Props {
  title: string;
  icon: Component;
  cards: DashboardCardData[];
  columnsClass?: string;
  columnsWrapperClassName?: string;
}

withDefaults(defineProps<Props>(), {
  columnsClass: 'is-one-third-tablet is-half-mobile',
  columnsWrapperClassName: '',
});
</script>
