// src/components/Avatar.tsx
import React, { useEffect, useRef, useState } from 'react';
import { ChevronDown, LogIn, LogOut, Settings, Star } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useGoogleLogin } from '@react-oauth/google';
import { useAuth } from '@/contexts/AuthContext';

type AvatarVariant = 'default' | 'compact';

interface AvatarProps {
  variant?: AvatarVariant;
  fallbackPicture?: string;
  fallbackName?: string;
  fallbackEmail?: string;
}

const Avatar: React.FC<AvatarProps> = ({
  variant = 'default',
  fallbackPicture,
  fallbackName,
  fallbackEmail,
}) => {
  const { user, login, logout } = useAuth();
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();
  const googleClientId = import.meta.env.VITE_GOOGLE_CLIENT_ID;
  const hasValidClientId = Boolean(googleClientId && googleClientId.trim());
  const hasFallback = Boolean(fallbackPicture || fallbackName || fallbackEmail);
  const displayUser =
    user ??
    (hasFallback
      ? {
          picture: fallbackPicture ?? 'https://i.pravatar.cc/150?u=telma-guest',
          name: fallbackName ?? 'Guest',
          email: fallbackEmail,
        }
      : null);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  if (!displayUser) {
    return null;
  }

  const handleNavigate = (path: string) => {
    navigate(path);
    setIsOpen(false);
  };

  const handleLogin = useGoogleLogin({
    onSuccess: (tokenResponse) => {
      login(tokenResponse);
      setIsOpen(false);
    },
    onError: () => {
      console.log('Login Failed');
    },
    scope: 'https://www.googleapis.com/auth/drive.appdata',
  });

  const handleLogout = () => {
    logout();
    setIsOpen(false);
  };

  return (
    <div className="avatar-menu" ref={dropdownRef}>
      <button
        type="button"
        className={`avatar-trigger ${isOpen ? 'is-open' : ''} ${variant === 'compact' ? 'is-compact' : ''}`}
        onClick={() => setIsOpen((prev) => !prev)}
        aria-haspopup="menu"
        aria-expanded={isOpen}
      >
        <img src={displayUser.picture} alt="User avatar" className="avatar-image" />
        {variant === 'default' && (
          <div className="avatar-text">
            <span className="avatar-name">{displayUser.name}</span>
            {displayUser.email && <span className="avatar-email">{displayUser.email}</span>}
          </div>
        )}
        <ChevronDown size={16} className="avatar-caret" />
      </button>

      {isOpen && (
        <div className="avatar-dropdown" role="menu">
          {!user && hasValidClientId && (
            <button
              type="button"
              className="avatar-menu-item"
              onClick={() => handleLogin()}
            >
              <LogIn size={18} />
              <span>Sign in with Google</span>
            </button>
          )}
          <button
            type="button"
            className="avatar-menu-item"
            onClick={() => handleNavigate('/dashboard')}
          >
            <Settings size={18} />
            <span>Settings</span>
          </button>
          <button
            type="button"
            className="avatar-menu-item"
            onClick={() => handleNavigate('/favorites')}
          >
            <Star size={18} />
            <span>Favorites</span>
          </button>
          {user && (
            <button
              type="button"
              className="avatar-menu-item is-danger"
              onClick={handleLogout}
            >
              <LogOut size={18} />
              <span>Logout</span>
            </button>
          )}
        </div>
      )}
    </div>
  );
};

export default Avatar;

// src/components/Avatar.vue
<template>
  <div v-if="displayUser" ref="dropdownRef" class="avatar-menu">
    <button
      type="button"
      :class="['avatar-trigger', { 'is-open': isOpen, 'is-compact': variant === 'compact' }]"
      @click="isOpen = !isOpen"
      aria-haspopup="menu"
      :aria-expanded="isOpen"
    >
      <img :src="displayUser.picture" alt="User avatar" class="avatar-image" />
      <div v-if="variant === 'default'" class="avatar-text">
        <span class="avatar-name">{{ displayUser.name }}</span>
        <span v-if="displayUser.email" class="avatar-email">{{ displayUser.email }}</span>
      </div>
      <ChevronDown :size="16" class="avatar-caret" />
    </button>

    <div v-if="isOpen" class="avatar-dropdown" role="menu">
      <button
        v-if="!user.value && hasValidClientId"
        type="button"
        class="avatar-menu-item"
        @click="handleLogin()"
      >
        <LogIn :size="18" />
        <span>Sign in with Google</span>
      </button>
      <button
        type="button"
        class="avatar-menu-item"
        @click="handleNavigate('/dashboard')"
      >
        <Settings :size="18" />
        <span>Settings</span>
      </button>
      <button
        type="button"
        class="avatar-menu-item"
        @click="handleNavigate('/favorites')"
      >
        <Star :size="18" />
        <span>Favorites</span>
      </button>
      <button
        v-if="user.value"
        type="button"
        class="avatar-menu-item is-danger"
        @click="handleLogout"
      >
        <LogOut :size="18" />
        <span>Logout</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { useRouter } from 'vue-router';
import { ChevronDown, LogIn, LogOut, Settings, Star } from 'lucide-vue-next';
import { useAuth } from '@/composables/useAuth';
import { useGoogleLogin } from '@/utils/googleOAuth';

type AvatarVariant = 'default' | 'compact';

interface Props {
  variant?: AvatarVariant;
  fallbackPicture?: string;
  fallbackName?: string;
  fallbackEmail?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default'
});

const { user, login, logout } = useAuth();
const router = useRouter();
const isOpen = ref(false);
const dropdownRef = ref<HTMLElement | null>(null);
const googleClientId = import.meta.env.VITE_GOOGLE_CLIENT_ID;
const hasValidClientId = computed(() => Boolean(googleClientId && googleClientId.trim()));
const hasFallback = computed(() => Boolean(props.fallbackPicture || props.fallbackName || props.fallbackEmail));

const displayUser = computed(() => {
  const currentUser = user.value;
  if (currentUser) return currentUser;
  if (hasFallback.value) {
    return {
      picture: props.fallbackPicture ?? 'https://i.pravatar.cc/150?u=telma-guest',
      name: props.fallbackName ?? 'Guest',
      email: props.fallbackEmail
    };
  }
  return null;
});

onMounted(() => {
  const handleClickOutside = (event: MouseEvent) => {
    if (dropdownRef.value && !dropdownRef.value.contains(event.target as Node)) {
      isOpen.value = false;
    }
  };
  document.addEventListener('mousedown', handleClickOutside);
  onUnmounted(() => {
    document.removeEventListener('mousedown', handleClickOutside);
  });
});

const handleNavigate = (path: string) => {
  router.push(path);
  isOpen.value = false;
};

const handleLoginClick = useGoogleLogin({
  onSuccess: (tokenResponse) => {
    login(tokenResponse.access_token);
    isOpen.value = false;
  },
  onError: () => {
    console.log('Login Failed');
  },
  scope: 'https://www.googleapis.com/auth/drive.appdata'
});

const handleLogin = () => {
  handleLoginClick();
};

const handleLogout = () => {
  logout();
  isOpen.value = false;
};
</script>
