// src/components/BottomNavbar.vue
<template>
  <nav class="bottom-navbar" role="navigation" aria-label="main navigation">
    <div class="bottom-navbar-menu">
      <RouterLink to="/" end class="bottom-navbar-item">
        <span class="icon"><Home :size="20" /></span>
        <span class="bottom-navbar-item-label">Home</span>
      </RouterLink>
      <RouterLink to="/itinerary" class="bottom-navbar-item">
        <span class="icon"><Route :size="20" /></span>
        <span class="bottom-navbar-item-label">Trajet</span>
      </RouterLink>
      <RouterLink to="/schedules" class="bottom-navbar-item">
        <span class="icon"><Clock :size="20" /></span>
        <span class="bottom-navbar-item-label">Horaires</span>
      </RouterLink>
      <button class="bottom-navbar-item" @click="onMoreClick">
        <span class="icon"><MoreHorizontal :size="20" /></span>
        <span class="bottom-navbar-item-label">More</span>
      </button>
      <RouterLink to="/favorites" class="bottom-navbar-item">
        <span class="icon"><Star :size="20" /></span>
        <span class="bottom-navbar-item-label">Favoris</span>
      </RouterLink>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { Home, Route, Clock, Star, MoreHorizontal } from 'lucide-vue-next';

interface Props {
  onMoreClick: () => void;
}

defineProps<Props>();
</script>

// src/components/BottomNavbar.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import { useSidebar } from '@/contexts/SidebarContext';
import { Home, Route, Clock, Star, MoreHorizontal } from 'lucide-react';

interface BottomNavbarProps {
    onMoreClick: () => void;
}

const BottomNavbar: React.FC<BottomNavbarProps> = ({ onMoreClick }) => {
    return (
        <nav className='bottom-navbar' role='navigation' aria-label='main navigation'>
            <div className='bottom-navbar-menu'>
                <NavLink to='/' end className='bottom-navbar-item'>
                    <span className='icon'><Home size={20} /></span>
                    <span className='bottom-navbar-item-label'>Home</span>
                </NavLink>
                <NavLink to='/itinerary' className='bottom-navbar-item'>
                    <span className='icon'><Route size={20} /></span>
                    <span className='bottom-navbar-item-label'>Trajet</span>
                </NavLink>
                <NavLink to='/schedules' className='bottom-navbar-item'>
                    <span className='icon'><Clock size={20} /></span>
                    <span className='bottom-navbar-item-label'>Horaires</span>
                </NavLink>
                <button className='bottom-navbar-item' onClick={onMoreClick}>
                    <span className='icon'><MoreHorizontal size={20} /></span>
                    <span className='bottom-navbar-item-label'>More</span>
                </button>
                <NavLink to='/favorites' className='bottom-navbar-item'>
                    <span className='icon'><Star size={20} /></span>
                    <span className='bottom-navbar-item-label'>Favoris</span>
                </NavLink>
            </div>
        </nav>
    );
}

export default BottomNavbar;
