// src/components/Footer.jsx
import React from 'react'

const Footer = () => {
  return (
    <footer className='footer has-background-primary has-text-white'>
      <div className='content has-text-centered'>
        <p className='has-text-white'>
          <span>&copy;</span> {new Date().getFullYear()} SNCF API Explorer
        </p>
        <p className='has-text-white is-size-7 mt-2'>
          Powered by Navitia API
        </p>
      </div>
    </footer>
  )
}

export default Footer

// src/components/Footer.vue
<template>
  <footer class="footer has-background-primary has-text-white">
    <div class="content has-text-centered">
      <p class="has-text-white">
        <span>&copy;</span> {{ new Date().getFullYear() }} SNCF API Explorer
      </p>
      <p class="has-text-white is-size-7 mt-2">
        Powered by Navitia API
      </p>
      <p class="has-text-white is-size-7 mt-2">
        Version {{ version }}
      </p>
    </div>
  </footer>
</template>

<script setup lang="ts">
import packageJson from '../../package.json';

const version = packageJson.version;
</script>
