// src/components/TrainStation.vue
<template>
  <div class="train-station">
    <div class="directions">
      <button
        type="button"
        :class="['directions__departures', { 'directions__departures--active': departureMode }]"
        @click="setDepartureMode(true)"
        @keypress="setDepartureMode(true)"
      >
        Départs
      </button>
      <button
        type="button"
        :class="['directions__arrivals', { 'directions__arrivals--active': !departureMode }]"
        @click="setDepartureMode(false)"
        @keypress="setDepartureMode(false)"
      >
        Arrivées
      </button>
    </div>
    <Departures v-if="departureMode" />
    <Arrivals v-if="!departureMode" />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import Arrivals from './Arrivals.vue';
import Departures from './Departures.vue';

const departureMode = ref<boolean>(true);

const setDepartureMode = (value: boolean) => {
  departureMode.value = value;
};
</script>

// src/components/TrainStation.tsx
import React, { useState } from 'react'
import Arrivals from './Arrivals'
import Departures from './Departures'

const TrainStation: React.FC = () => {
    const [departureMode, setDepartureMode] = useState<boolean>(true)

    return (
        <div className='train-station'>
            <div className='directions'>
                <button
                    type='button'
                    className={`directions__departures ${departureMode ? 'directions__departures--active' : ''}`}
                    onClick={() => setDepartureMode(true)}
                    onKeyPress={() => setDepartureMode(true)}
                >
                    Départs
                </button>
                <button
                    type='button'
                    className={`directions__arrivals ${departureMode ? '' : 'directions__arrivals--active'}`}
                    onClick={() => setDepartureMode(false)}
                    onKeyPress={() => setDepartureMode(false)}
                >
                    Arrivées
                </button>
            </div>
            {departureMode && <Departures />}
            {!departureMode && <Arrivals />}
        </div>
    )
}

export default TrainStation
