// src/components/train/TrainErrorState.vue
<template>
  <section class="section">
    <div class="container">
      <div class="box has-text-centered">
        <span class="icon is-large has-text-danger">
          <AlertTriangle :size="48" />
        </span>
        <p class="mt-4 has-text-danger">{{ error || 'Train non trouvé' }}</p>
        <div class="buttons is-centered mt-4">
          <button
            class="button is-primary"
            @click="$emit('refresh')"
            :disabled="refreshing"
          >
            <span class="icon">
              <Loader2 v-if="refreshing" :size="16" class="animate-spin" />
              <RefreshCw v-else :size="16" />
            </span>
            <span>{{ refreshing ? 'Actualisation...' : 'Actualiser' }}</span>
          </button>
          <RouterLink to="/train" class="button is-light">
            Rechercher un autre train
          </RouterLink>
        </div>
      </div>
    </div>
  </section>
  <Footer />
</template>

<script setup lang="ts">
import { AlertTriangle, Loader2, RefreshCw } from 'lucide-vue-next';
import Footer from '@/components/Footer.vue';

interface Props {
  error: string | null;
  refreshing: boolean;
}

defineProps<Props>();

defineEmits<{
  refresh: [];
}>();
</script>

// src/components/train/TrainErrorState.tsx
import React from 'react';
import { AlertTriangle, Loader2, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import Footer from '@/components/Footer';

interface TrainErrorStateProps {
    error: string | null;
    onRefresh: () => void;
    refreshing: boolean;
}

const TrainErrorState: React.FC<TrainErrorStateProps> = ({ error, onRefresh, refreshing }) => {
    return (
        <>
            <section className='section'>
                <div className='container'>
                    <div className='box has-text-centered'>
                        <span className='icon is-large has-text-danger'>
                            <AlertTriangle size={48} />
                        </span>
                        <p className='mt-4 has-text-danger'>{error || 'Train non trouvé'}</p>
                        <div className='buttons is-centered mt-4'>
                            <button 
                                className='button is-primary' 
                                onClick={onRefresh}
                                disabled={refreshing}
                            >
                                <span className='icon'>
                                    {refreshing ? <Loader2 size={16} className="animate-spin" /> : <RefreshCw size={16} />}
                                </span>
                                <span>{refreshing ? 'Actualisation...' : 'Actualiser'}</span>
                            </button>
                            <Link to='/train' className='button is-light'>
                                Rechercher un autre train
                            </Link>
                        </div>
                    </div>
                </div>
            </section>
            <Footer />
        </>
    );
};

export default TrainErrorState;
