// src/components/train/TrainStopTimesTable.tsx
import React from 'react';
import { parseUTCDate, formatTime } from '@/utils/dateUtils';
import { calculateDelay } from '@/services/delayService';
import type { ExtendedVehicleJourney } from './types';

interface TrainStopTimesTableProps {
    stopTimes: NonNullable<ExtendedVehicleJourney['stop_times']>;
}

const TrainStopTimesTable: React.FC<TrainStopTimesTableProps> = ({ stopTimes }) => {
    if (stopTimes.length === 0) {
        return null;
    }

    return (
        <div className='box'>
            <h3 className='title is-4 mb-4'>Arrêts et horaires</h3>
            <div className='table-container'>
                <table className='table is-fullwidth is-striped is-hoverable'>
                    <thead>
                        <tr>
                            <th>Gare</th>
                            <th>Horaire prévu</th>
                            <th>Horaire réel</th>
                            <th>Retard</th>
                            <th>Quai/Voie</th>
                        </tr>
                    </thead>
                    <tbody>
                        {stopTimes.map((stop, index) => {
                            const extendedStop = stop as NonNullable<ExtendedVehicleJourney['stop_times']>[0];
                            const baseArrival = extendedStop?.base_arrival_date_time;
                            const realArrival = extendedStop?.arrival_date_time;
                            const baseDeparture = extendedStop?.base_departure_date_time;
                            const realDeparture = extendedStop?.departure_date_time;
                            
                            // Use arrival for intermediate stops, departure for last stop
                            const baseTime = index === stopTimes.length - 1 ? baseDeparture : baseArrival;
                            const realTime = index === stopTimes.length - 1 ? realDeparture : realArrival;

                            // Only calculate delay if both times are available
                            let delay: string | null = null;
                            if (baseTime && realTime) {
                                try {
                                    delay = calculateDelay(
                                        parseUTCDate(baseTime),
                                        parseUTCDate(realTime)
                                    );
                                } catch (err) {
                                    delay = null;
                                }
                            }

                            const stopPoint = extendedStop?.stop_point || {};
                            const stopArea = (stopPoint as { stop_area?: { name?: string | null } }).stop_area || {};
                            const stopName = (stopPoint as { name?: string | null }).name || stopArea?.name || 'Gare inconnue';
                            const platform = (stopPoint as { label?: string | null }).label || 'N/A';

                            return (
                                <tr key={index}>
                                    <td>
                                        <strong>{stopName}</strong>
                                        {index === 0 && (
                                            <span className='tag is-success is-dark ml-2'>Départ</span>
                                        )}
                                        {index === stopTimes.length - 1 && (
                                            <span className='tag is-danger is-dark ml-2'>Arrivée</span>
                                        )}
                                    </td>
                                    <td>{baseTime ? formatTime(parseUTCDate(baseTime)) : 'N/A'}</td>
                                    <td>
                                        {realTime && realTime !== baseTime ? (
                                            <span className='has-text-danger'>{formatTime(parseUTCDate(realTime))}</span>
                                        ) : baseTime ? (
                                            formatTime(parseUTCDate(baseTime))
                                        ) : (
                                            'N/A'
                                        )}
                                    </td>
                                    <td>
                                        {delay ? (
                                            delay !== 'À l\'heure' && delay !== 'à l\'heure' ? (
                                                <span className='tag is-danger'>{delay}</span>
                                            ) : (
                                                <span className='tag is-success'>À l'heure</span>
                                            )
                                        ) : (
                                            <span className='tag is-dark'>N/A</span>
                                        )}
                                    </td>
                                    <td>{platform}</td>
                                </tr>
                            );
                        })}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default TrainStopTimesTable;

// src/components/train/TrainStopTimesTable.vue
<template>
  <div v-if="stopTimes.length > 0" class="box">
    <h3 class="title is-4 mb-4">Arrêts et horaires</h3>
    <div class="table-container">
      <table class="table is-fullwidth is-striped is-hoverable">
        <thead>
          <tr>
            <th>Gare</th>
            <th>Horaire prévu</th>
            <th>Horaire réel</th>
            <th>Retard</th>
            <th>Quai/Voie</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(stop, index) in stopTimes" :key="index">
            <td>
              <strong>{{ getStopName(stop, index) }}</strong>
              <span v-if="index === 0" class="tag is-success is-dark ml-2">Départ</span>
              <span v-if="index === stopTimes.length - 1" class="tag is-danger is-dark ml-2">Arrivée</span>
            </td>
            <td>{{ getBaseTime(stop, index) }}</td>
            <td>
              <span v-if="getRealTime(stop, index) && getRealTime(stop, index) !== getBaseTime(stop, index)" class="has-text-danger">
                {{ getRealTime(stop, index) }}
              </span>
              <span v-else>{{ getBaseTime(stop, index) }}</span>
            </td>
            <td>
              <span v-if="getDelay(stop, index)" :class="getDelayClass(getDelay(stop, index))">
                {{ getDelay(stop, index) }}
              </span>
              <span v-else>—</span>
            </td>
            <td>{{ getPlatform(stop) }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { parseUTCDate, formatTime } from '@/utils/dateUtils';
import { calculateDelay } from '@/services/delayService';
import type { ExtendedVehicleJourney } from './types';

interface Props {
  stopTimes: NonNullable<ExtendedVehicleJourney['stop_times']>;
}

const props = defineProps<Props>();

const getStopName = (stop: any, index: number): string => {
  const stopPoint = stop?.stop_point || {};
  const stopArea = stopPoint?.stop_area || {};
  return stopPoint?.name || stopArea?.name || 'Gare inconnue';
};

const getBaseTime = (stop: any, index: number): string => {
  const isLast = index === props.stopTimes.length - 1;
  const baseTime = isLast ? stop?.base_departure_date_time : stop?.base_arrival_date_time;
  return baseTime ? formatTime(parseUTCDate(baseTime)) : 'N/A';
};

const getRealTime = (stop: any, index: number): string | null => {
  const isLast = index === props.stopTimes.length - 1;
  const realTime = isLast ? stop?.departure_date_time : stop?.arrival_date_time;
  return realTime ? formatTime(parseUTCDate(realTime)) : null;
};

const getDelay = (stop: any, index: number): string | null => {
  const isLast = index === props.stopTimes.length - 1;
  const baseTime = isLast ? stop?.base_departure_date_time : stop?.base_arrival_date_time;
  const realTime = isLast ? stop?.departure_date_time : stop?.arrival_date_time;
  
  if (baseTime && realTime) {
    try {
      return calculateDelay(
        parseUTCDate(baseTime),
        parseUTCDate(realTime)
      );
    } catch (err) {
      return null;
    }
  }
  return null;
};

const getDelayClass = (delay: string | null): string => {
  if (!delay) return '';
  const delayMinutes = parseInt(delay.replace(/[^0-9]/g, ''));
  if (delayMinutes > 10) return 'has-text-danger';
  if (delayMinutes > 5) return 'has-text-warning';
  return '';
};

const getPlatform = (stop: any): string => {
  return stop?.stop_point?.label || 'N/A';
};
</script>
