// src/components/itinerary/ItinerarySearchForm.tsx
import React from 'react';
import { Search, ArrowLeftRight } from 'lucide-react';
import LocationAutocomplete from '@/components/LocationAutocomplete';
import type { Place } from '@/client/models/place';

interface ItinerarySearchFormProps {
    fromName: string;
    toName: string;
    fromId: string | undefined;
    toId: string | undefined;
    filterDate: string;
    filterTime: string;
    loading: boolean;
    onFromChange: (id: string | undefined) => void;
    onToChange: (id: string | undefined) => void;
    onFromValueChange: (value: string) => void;
    onToValueChange: (value: string) => void;
    onFromStationFound: (station: Place & { name?: string | null }) => void;
    onToStationFound: (station: Place & { name?: string | null }) => void;
    onFilterDateChange: (date: string) => void;
    onFilterTimeChange: (time: string) => void;
    onSearch: () => void;
    onInvertItinerary: () => void;
}

const ItinerarySearchForm: React.FC<ItinerarySearchFormProps> = ({
    fromName,
    toName,
    fromId,
    toId,
    filterDate,
    filterTime,
    loading,
    onFromChange,
    onToChange,
    onFromValueChange,
    onToValueChange,
    onFromStationFound,
    onToStationFound,
    onFilterDateChange,
    onFilterTimeChange,
    onSearch,
    onInvertItinerary,
}) => {
    return (
        <div className='box mb-5'>
            <h3 className='title is-5 mb-4'>Recherche d'itinéraire</h3>
            <div className='columns'>
                <div className='column'>
                    <LocationAutocomplete
                        label='Gare de départ'
                        value={fromName}
                        onValueChange={onFromValueChange}
                        onChange={onFromChange}
                        defaultSearchTerm={fromName || 'Metz'}
                        onStationFound={onFromStationFound}
                        disabled={loading}
                    />
                </div>
                <div className='column is-narrow'>
                    <div className='field'>
                        <label className='label'>&nbsp;</label>
                        <div className='control'>
                            <button
                                className='button is-light'
                                onClick={onInvertItinerary}
                                disabled={loading || !fromId || !toId}
                                title="Inverser l'itinéraire"
                            >
                                <span className='icon'>
                                    <ArrowLeftRight size={20} />
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
                <div className='column'>
                    <LocationAutocomplete
                        label="Gare d'arrivée"
                        value={toName}
                        onValueChange={onToValueChange}
                        onChange={onToChange}
                        defaultSearchTerm={toName || 'Thionville'}
                        onStationFound={onToStationFound}
                        disabled={loading}
                    />
                </div>
            </div>
            <div className='columns mt-4'>
                <div className='column is-narrow'>
                    <div className='field'>
                        <label className='label'>Date</label>
                        <div className='control'>
                            <input
                                className='input'
                                type='date'
                                value={filterDate}
                                onChange={(e: React.ChangeEvent<HTMLInputElement>) => onFilterDateChange(e.target.value)}
                                disabled={loading}
                            />
                        </div>
                    </div>
                </div>
                <div className='column is-narrow'>
                    <div className='field'>
                        <label className='label'>Heure</label>
                        <div className='control'>
                            <input
                                className='input'
                                type='time'
                                value={filterTime}
                                onChange={(e: React.ChangeEvent<HTMLInputElement>) => onFilterTimeChange(e.target.value)}
                                disabled={loading}
                            />
                        </div>
                    </div>
                </div>
                <div className='column is-narrow'>
                    <div className='field'>
                        <label className='label'>&nbsp;</label>
                        <div className='control'>
                            <button
                                className='button is-primary'
                                onClick={onSearch}
                                disabled={loading || !fromId || !toId}
                            >
                                <span className='icon'><Search size={16} /></span>
                                <span>Rechercher</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ItinerarySearchForm;

// src/components/itinerary/ItinerarySearchForm.vue
<template>
  <div class="box mb-5">
    <h3 class="title is-5 mb-4">Recherche d'itinéraire</h3>
    <div class="columns">
      <div class="column">
        <LocationAutocomplete
          label="Gare de départ"
          :value="fromName"
          @value-change="$emit('from-value-change', $event)"
          @change="$emit('from-change', $event)"
          :default-search-term="fromName || 'Metz'"
          @station-found="$emit('from-station-found', $event)"
          :disabled="loading"
        />
      </div>
      <div class="column is-narrow">
        <div class="field">
          <label class="label">&nbsp;</label>
          <div class="control">
            <button
              class="button is-light"
              @click="$emit('invert-itinerary')"
              :disabled="loading || !fromId || !toId"
              title="Inverser l'itinéraire"
            >
              <span class="icon">
                <ArrowLeftRight :size="20" />
              </span>
            </button>
          </div>
        </div>
      </div>
      <div class="column">
        <LocationAutocomplete
          label="Gare d'arrivée"
          :value="toName"
          @value-change="$emit('to-value-change', $event)"
          @change="$emit('to-change', $event)"
          :default-search-term="toName || 'Thionville'"
          @station-found="$emit('to-station-found', $event)"
          :disabled="loading"
        />
      </div>
    </div>
    <div class="columns mt-4">
      <div class="column is-narrow">
        <div class="field">
          <label class="label">Date</label>
          <div class="control">
            <input
              class="input"
              type="date"
              :value="filterDate"
              @input="$emit('filter-date-change', ($event.target as HTMLInputElement).value)"
              :disabled="loading"
            />
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="field">
          <label class="label">Heure</label>
          <div class="control">
            <input
              class="input"
              type="time"
              :value="filterTime"
              @input="$emit('filter-time-change', ($event.target as HTMLInputElement).value)"
              :disabled="loading"
            />
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="field">
          <label class="label">&nbsp;</label>
          <div class="control">
            <button
              class="button is-primary"
              @click="$emit('search')"
              :disabled="loading || !fromId || !toId"
            >
              <span class="icon"><Search :size="16" /></span>
              <span>Rechercher</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Search, ArrowLeftRight } from 'lucide-vue-next';
import LocationAutocomplete from '@/components/LocationAutocomplete.vue';
import type { Place } from '@/client/models/place';

interface Props {
  fromName: string;
  toName: string;
  fromId: string | undefined;
  toId: string | undefined;
  filterDate: string;
  filterTime: string;
  loading: boolean;
}

defineProps<Props>();

defineEmits<{
  'from-change': [id: string | undefined];
  'to-change': [id: string | undefined];
  'from-value-change': [value: string];
  'to-value-change': [value: string];
  'from-station-found': [station: Place & { name?: string | null }];
  'to-station-found': [station: Place & { name?: string | null }];
  'filter-date-change': [date: string];
  'filter-time-change': [time: string];
  'search': [];
  'invert-itinerary': [];
}>();
</script>
