// src/components/commercialModes/CommercialModesErrorState.tsx
import React from 'react';

interface CommercialModesErrorStateProps {
    error: string;
    onDismiss: () => void;
}

const CommercialModesErrorState: React.FC<CommercialModesErrorStateProps> = ({ error, onDismiss }) => {
    return (
        <div className='notification is-danger'>
            <button className='delete' onClick={onDismiss}></button>
            <p className='title is-5'>Erreur</p>
            <p>{error}</p>
        </div>
    );
};

export default CommercialModesErrorState;

// src/components/commercialModes/CommercialModesErrorState.vue
<template>
  <div class="notification is-danger">
    <button class="delete" @click="$emit('dismiss')"></button>
    <p class="title is-5">Erreur</p>
    <p>{{ error }}</p>
  </div>
</template>

<script setup lang="ts">
interface Props {
  error: string;
}

defineProps<Props>();

defineEmits<{
  dismiss: [];
}>();
</script>
